version: '3'
services: 
 db:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - vol-admin-mysql:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: root
    ports:
     - "3308:3306"
    networks:
     - net
    
 web:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on: 
     - db
    ports:
     - "8080:80"
    networks:
     - net
volumes: 
 vol-admin-mysql:
networks: 
 net: